#!/bin/bash -l

#$ -l h_rt=96:00:00

#$ -m e

#$ -j y

#$ -N on_off_RL_from_observations_AWAC_Q_lambda_TB_ri_0.1

#$ -V

#$ -pe omp 4
#$ -l mem_per_core=4G

module load miniconda

conda activate /project/onr/vgiammar/RL_env
python main.py --mode on_off_RL_from_observations --env Image48HumanLikeSawyerPushForwardEnv-v1 --policy AWAC_Q_lambda_TB --max_iter 250 --intrinsic_reward 0.1 --domain_adaptation --load_encoder --seed $1
